api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    swarmMode: true
    endpoint: "unix:///var/run/docker.sock"

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"



certificatesResolvers:
  myresolver:
    acme:
      email: <your_email@example.com>
      storage: acme.json
      httpChallenge:
        entryPoint: web
