version: '3.3'

services:
  catapp:
     networks:
      - inbound
     image: mikesir87/cats:1.0
     deploy:
      labels:
        - "traefik.enable=true"
    # Routers
        - "traefik.http.routers.catapp.rule=Host(`catapp.localhost`)"
        - "traefik.http.routers.catapp.entrypoints=web"
        - "traefik.http.routers.catapp.middlewares=test-redirectscheme"
        - "traefik.http.routers.catapp-secure.rule=Host(`catapp.localhost`)"
        - "traefik.http.routers.catapp-secure.entrypoints=websecure"
        - "traefik.http.routers.catapp-secure.tls.certresolver=myresolver"
        - "traefik.http.routers.catapp-secure.middlewares=basic-auth,test-compress,test-errorpages,test-ratelimit,my-traefik-themepark@file"

    # Services
        - "traefik.http.services.catapp.loadbalancer.server.port=5000"
    
    # BasicAuth Middleware
        - "traefik.http.middlewares.basic-auth.basicauth.users=traefik:$$apr1$$.zPbdVg8$$LcHeyCZElH.JfxkxxlMPI.,user2:$$apr1$$XDrP1Fb1$$SZqSEjvNYW44vgJgI3iEP0"
      
    # Compress Middleware
        - "traefik.http.middlewares.test-compress.compress=true"

    # Rate Limit Middleware
        - "traefik.http.middlewares.test-ratelimit.ratelimit.average=2"

    # Error Pages Middleware
        - "traefik.http.middlewares.test-errorpages.errors.status=400-599"
        - "traefik.http.middlewares.test-errorpages.errors.service=error"
        - "traefik.http.middlewares.test-errorpages.errors.query=/{status}.html"

    # Redirect Scheme HTTP -> HTTPS
        - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
        - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
        - "traefik.docker.network=inbound"
networks:
  inbound:
    external: true



