version: '3.7'

services:
  whoami:
      image: traefik/whoami
      networks:
        - traefik-public
      deploy:
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
          - "traefik.http.routers.whoami.entrypoints=web"
          - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true