version: '3.3'

services:
  traefik:
    image: traefik:v3.0
    networks:
      - inbound
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./config.yml:/etc/traefik/config.yml
      - ./maintenance_test.html:/etc/traefik/maintenance_test.html

networks:
  inbound:
    external: true



