version: '3.3'

services:
  scaler:
    build: ./
    image: scaler_pottuscaler:latest
    networks:
      - inbound
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.enable=false"
        - "traefik.docker.network=inbound"

networks:
  inbound:
    external: true