version: '3.3'

services:
  traefik-dockerproxy:
    environment:
      CONTAINERS: 1 # gives access to /api/containers
    image: tecnativa/docker-socket-proxy
    networks:
      - traefik
    ports:
      - 2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
    image: traefik:v3.0
    depends_on:
      - traefik-dockerproxy
    networks:
      - traefik
      - public
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # The Web UI port. traefik.yml - dashboard: true
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml

  whoami:
      # A container that exposes an API to show its IP address
      image: traefik/whoami
      networks:
       - public
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"

networks:
  traefik:
    name: traefik
  public:
    name: public