version: '3.3'

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.5
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml

# Add the catapp service
  catapp:
     # A Random Cat GIF generator application
     image: mikesir87/cats:1.0
     # We set a label to tell Traefik to assign a hostname to the new service
     deploy:
      labels:
        - "traefik.enable=true"
    # Routers
        - "traefik.http.routers.catapp.rule=Host(`catapp.localhost`)"
        - "traefik.http.routers.catapp.entrypoints=web"
        - "traefik.http.routers.catapp.middlewares=test-redirectscheme"
        
        - "traefik.http.routers.catapp-secure.rule=Host(`catapp.localhost`)"
        - "traefik.http.routers.catapp-secure.entrypoints=websecure"
        - "traefik.http.routers.catapp-secure.tls.certresolver=myresolver"
        - "traefik.http.routers.catapp-secure.middlewares=basic-auth,test-compress,test-errorpages,test-ratelimit"

    # Services
        - "traefik.http.services.catapp.loadbalancer.server.port=5000"
    
    # BasicAuth Middleware
        - "traefik.http.middlewares.basic-auth.basicauth.users=traefik:$$apr1$$.zPbdVg8$$LcHeyCZElH.JfxkxxlMPI.,user2:$$apr1$$XDrP1Fb1$$SZqSEjvNYW44vgJgI3iEP0"
      
    # Compress Middleware
        - "traefik.http.middlewares.test-compress.compress=true"

    # Rate Limit Middleware
        - "traefik.http.middlewares.test-ratelimit.ratelimit.average=2"

    # Error Pages Middleware
        - "traefik.http.middlewares.test-errorpages.errors.status=400-599"
        - "traefik.http.middlewares.test-errorpages.errors.service=error"
        - "traefik.http.middlewares.test-errorpages.errors.query=/{status}.html"

    # Redirect Scheme HTTP -> HTTPS
        - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
        - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"

  whoami:
      # A container that exposes an API to show its IP address
      image: traefik/whoami
      deploy:
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
          - "traefik.http.routers.whoami.entrypoints=web"
          - "traefik.http.services.whoami.loadbalancer.server.port=80"
          - "traefik.http.services.whoami.loadbalancer.sticky.cookie=true"
          - "traefik.http.services.whoami.loadbalancer.sticky.cookie.name=stickysvr"

# Error Page service
  error:
    image: guillaumebriday/traefik-custom-error-pages
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.error.rule=Host(`error.localhost`)"
        - "traefik.http.routers.error.service=error"
        - "traefik.http.services.error.loadbalancer.server.port=80"
        - "traefik.http.routers.error.entrypoints=web"